namespace SPLAT
{
	// Token: 0x0200000B RID: 11
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class ContentPack : global::System.Windows.Forms.Form
	{
		// Token: 0x06000026 RID: 38 RVA: 0x0007BFD4 File Offset: 0x0007A3D4
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000027 RID: 39 RVA: 0x0007C014 File Offset: 0x0007A414
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::SPLAT.ContentPack));
			this.DIP = new global::System.Windows.Forms.Button();
			this.Retooned = new global::System.Windows.Forms.Button();
			this.Nightlife = new global::System.Windows.Forms.Button();
			this.HappyDays = new global::System.Windows.Forms.Button();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.RetoonedTTPA = new global::System.Windows.Forms.Button();
			this.DIPTTPA = new global::System.Windows.Forms.Button();
			this.NightlifeTTPA = new global::System.Windows.Forms.Button();
			this.HappyDaysTTPA = new global::System.Windows.Forms.Button();
			this.RetoonedTTR = new global::System.Windows.Forms.Button();
			this.DIPTTR = new global::System.Windows.Forms.Button();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.NIGHTLIFETTR = new global::System.Windows.Forms.Button();
			this.HappyDaysTTR = new global::System.Windows.Forms.Button();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.TTRUnistall = new global::System.Windows.Forms.Button();
			this.TTPAUnistall = new global::System.Windows.Forms.Button();
			this.SuspendLayout();
			this.DIP.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("DIP.BackgroundImage");
			this.DIP.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.DIP.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control dip = this.DIP;
			global::System.Drawing.Point location = new global::System.Drawing.Point(231, 149);
			dip.Location = location;
			this.DIP.Name = "DIP";
			global::System.Windows.Forms.Control dip2 = this.DIP;
			global::System.Drawing.Size size = new global::System.Drawing.Size(121, 28);
			dip2.Size = size;
			this.DIP.TabIndex = 0;
			this.DIP.Text = "DIP";
			this.DIP.UseVisualStyleBackColor = true;
			this.Retooned.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("Retooned.BackgroundImage");
			this.Retooned.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Retooned.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control retooned = this.Retooned;
			location = new global::System.Drawing.Point(406, 149);
			retooned.Location = location;
			this.Retooned.Name = "Retooned";
			global::System.Windows.Forms.Control retooned2 = this.Retooned;
			size = new global::System.Drawing.Size(116, 28);
			retooned2.Size = size;
			this.Retooned.TabIndex = 1;
			this.Retooned.Text = "Retooned";
			this.Retooned.UseVisualStyleBackColor = true;
			this.Nightlife.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("Nightlife.BackgroundImage");
			this.Nightlife.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Nightlife.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control nightlife = this.Nightlife;
			location = new global::System.Drawing.Point(231, 115);
			nightlife.Location = location;
			this.Nightlife.Name = "Nightlife";
			global::System.Windows.Forms.Control nightlife2 = this.Nightlife;
			size = new global::System.Drawing.Size(121, 28);
			nightlife2.Size = size;
			this.Nightlife.TabIndex = 3;
			this.Nightlife.Text = "Nightlife";
			this.Nightlife.UseVisualStyleBackColor = true;
			this.HappyDays.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("HappyDays.BackgroundImage");
			this.HappyDays.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.HappyDays.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control happyDays = this.HappyDays;
			location = new global::System.Drawing.Point(406, 115);
			happyDays.Location = location;
			this.HappyDays.Name = "HappyDays";
			global::System.Windows.Forms.Control happyDays2 = this.HappyDays;
			size = new global::System.Drawing.Size(116, 28);
			happyDays2.Size = size;
			this.HappyDays.TabIndex = 5;
			this.HappyDays.Text = "Happy Days";
			this.HappyDays.UseVisualStyleBackColor = true;
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Label1.Image");
			global::System.Windows.Forms.Control label = this.Label1;
			location = new global::System.Drawing.Point(269, 9);
			label.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			size = new global::System.Drawing.Size(207, 11);
			label2.Size = size;
			this.Label1.TabIndex = 7;
			this.Label1.Text = "Cranky's Toontown Customizer";
			this.Label4.AutoSize = true;
			this.Label4.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Label4.Image");
			global::System.Windows.Forms.Control label3 = this.Label4;
			location = new global::System.Drawing.Point(580, 519);
			label3.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label4 = this.Label4;
			size = new global::System.Drawing.Size(167, 11);
			label4.Size = size;
			this.Label4.TabIndex = 10;
			this.Label4.Text = "@2017 Cranky Supertoon";
			this.Label5.AutoSize = true;
			this.Label5.Font = new global::System.Drawing.Font("Minnie", 20.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label5.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Label5.Image");
			global::System.Windows.Forms.Control label5 = this.Label5;
			location = new global::System.Drawing.Point(0, 506);
			label5.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label6 = this.Label5;
			size = new global::System.Drawing.Size(90, 28);
			label6.Size = size;
			this.Label5.TabIndex = 11;
			this.Label5.Text = "v1.1.1";
			this.Label6.AutoSize = true;
			this.Label6.Font = new global::System.Drawing.Font("Minnie", 20.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label6.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Label6.Image");
			global::System.Windows.Forms.Control label7 = this.Label6;
			location = new global::System.Drawing.Point(582, 317);
			label7.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label8 = this.Label6;
			size = new global::System.Drawing.Size(70, 28);
			label8.Size = size;
			this.Label6.TabIndex = 13;
			this.Label6.Text = "TTR";
			this.Label7.AutoSize = true;
			this.Label7.Font = new global::System.Drawing.Font("Minnie", 20.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label7.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Label7.Image");
			global::System.Windows.Forms.Control label9 = this.Label7;
			location = new global::System.Drawing.Point(91, 317);
			label9.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label10 = this.Label7;
			size = new global::System.Drawing.Size(86, 28);
			label10.Size = size;
			this.Label7.TabIndex = 14;
			this.Label7.Text = "TTPA";
			this.RetoonedTTPA.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("RetoonedTTPA.BackgroundImage");
			this.RetoonedTTPA.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.RetoonedTTPA.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control retoonedTTPA = this.RetoonedTTPA;
			location = new global::System.Drawing.Point(139, 357);
			retoonedTTPA.Location = location;
			this.RetoonedTTPA.Name = "RetoonedTTPA";
			global::System.Windows.Forms.Control retoonedTTPA2 = this.RetoonedTTPA;
			size = new global::System.Drawing.Size(116, 28);
			retoonedTTPA2.Size = size;
			this.RetoonedTTPA.TabIndex = 15;
			this.RetoonedTTPA.Text = "Retooned";
			this.RetoonedTTPA.UseVisualStyleBackColor = true;
			this.DIPTTPA.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("DIPTTPA.BackgroundImage");
			this.DIPTTPA.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.DIPTTPA.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control dipttpa = this.DIPTTPA;
			location = new global::System.Drawing.Point(12, 357);
			dipttpa.Location = location;
			this.DIPTTPA.Name = "DIPTTPA";
			global::System.Windows.Forms.Control dipttpa2 = this.DIPTTPA;
			size = new global::System.Drawing.Size(121, 28);
			dipttpa2.Size = size;
			this.DIPTTPA.TabIndex = 16;
			this.DIPTTPA.Text = "DIP";
			this.DIPTTPA.UseVisualStyleBackColor = true;
			this.NightlifeTTPA.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("NightlifeTTPA.BackgroundImage");
			this.NightlifeTTPA.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.NightlifeTTPA.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control nightlifeTTPA = this.NightlifeTTPA;
			location = new global::System.Drawing.Point(13, 391);
			nightlifeTTPA.Location = location;
			this.NightlifeTTPA.Name = "NightlifeTTPA";
			global::System.Windows.Forms.Control nightlifeTTPA2 = this.NightlifeTTPA;
			size = new global::System.Drawing.Size(121, 28);
			nightlifeTTPA2.Size = size;
			this.NightlifeTTPA.TabIndex = 17;
			this.NightlifeTTPA.Text = "Nightlife";
			this.NightlifeTTPA.UseVisualStyleBackColor = true;
			this.HappyDaysTTPA.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("HappyDaysTTPA.BackgroundImage");
			this.HappyDaysTTPA.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.HappyDaysTTPA.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control happyDaysTTPA = this.HappyDaysTTPA;
			location = new global::System.Drawing.Point(139, 391);
			happyDaysTTPA.Location = location;
			this.HappyDaysTTPA.Name = "HappyDaysTTPA";
			global::System.Windows.Forms.Control happyDaysTTPA2 = this.HappyDaysTTPA;
			size = new global::System.Drawing.Size(116, 28);
			happyDaysTTPA2.Size = size;
			this.HappyDaysTTPA.TabIndex = 18;
			this.HappyDaysTTPA.Text = "Happy Days";
			this.HappyDaysTTPA.UseVisualStyleBackColor = true;
			this.RetoonedTTR.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("RetoonedTTR.BackgroundImage");
			this.RetoonedTTR.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.RetoonedTTR.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control retoonedTTR = this.RetoonedTTR;
			location = new global::System.Drawing.Point(618, 357);
			retoonedTTR.Location = location;
			this.RetoonedTTR.Name = "RetoonedTTR";
			global::System.Windows.Forms.Control retoonedTTR2 = this.RetoonedTTR;
			size = new global::System.Drawing.Size(116, 28);
			retoonedTTR2.Size = size;
			this.RetoonedTTR.TabIndex = 19;
			this.RetoonedTTR.Text = "Retooned";
			this.RetoonedTTR.UseVisualStyleBackColor = true;
			this.DIPTTR.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("DIPTTR.BackgroundImage");
			this.DIPTTR.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.DIPTTR.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control dipttr = this.DIPTTR;
			location = new global::System.Drawing.Point(491, 357);
			dipttr.Location = location;
			this.DIPTTR.Name = "DIPTTR";
			global::System.Windows.Forms.Control dipttr2 = this.DIPTTR;
			size = new global::System.Drawing.Size(121, 28);
			dipttr2.Size = size;
			this.DIPTTR.TabIndex = 20;
			this.DIPTTR.Text = "DIP";
			this.DIPTTR.UseVisualStyleBackColor = true;
			this.Button3.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("Button3.BackgroundImage");
			this.Button3.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button3.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control button = this.Button3;
			location = new global::System.Drawing.Point(970, 321);
			button.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button2 = this.Button3;
			size = new global::System.Drawing.Size(121, 28);
			button2.Size = size;
			this.Button3.TabIndex = 22;
			this.Button3.Text = "DIP";
			this.Button3.UseVisualStyleBackColor = true;
			this.NIGHTLIFETTR.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("NIGHTLIFETTR.BackgroundImage");
			this.NIGHTLIFETTR.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.NIGHTLIFETTR.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control nightlifettr = this.NIGHTLIFETTR;
			location = new global::System.Drawing.Point(491, 391);
			nightlifettr.Location = location;
			this.NIGHTLIFETTR.Name = "NIGHTLIFETTR";
			global::System.Windows.Forms.Control nightlifettr2 = this.NIGHTLIFETTR;
			size = new global::System.Drawing.Size(121, 28);
			nightlifettr2.Size = size;
			this.NIGHTLIFETTR.TabIndex = 21;
			this.NIGHTLIFETTR.Text = "Nightlife";
			this.NIGHTLIFETTR.UseVisualStyleBackColor = true;
			this.HappyDaysTTR.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("HappyDaysTTR.BackgroundImage");
			this.HappyDaysTTR.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.HappyDaysTTR.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control happyDaysTTR = this.HappyDaysTTR;
			location = new global::System.Drawing.Point(618, 391);
			happyDaysTTR.Location = location;
			this.HappyDaysTTR.Name = "HappyDaysTTR";
			global::System.Windows.Forms.Control happyDaysTTR2 = this.HappyDaysTTR;
			size = new global::System.Drawing.Size(116, 28);
			happyDaysTTR2.Size = size;
			this.HappyDaysTTR.TabIndex = 23;
			this.HappyDaysTTR.Text = "Happy Days";
			this.HappyDaysTTR.UseVisualStyleBackColor = true;
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("Minnie", 20.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Label2.Image");
			global::System.Windows.Forms.Control label11 = this.Label2;
			location = new global::System.Drawing.Point(318, 56);
			label11.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label12 = this.Label2;
			size = new global::System.Drawing.Size(111, 28);
			label12.Size = size;
			this.Label2.TabIndex = 24;
			this.Label2.Text = "Step 1";
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Minnie", 20.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Label3.Image");
			global::System.Windows.Forms.Control label13 = this.Label3;
			location = new global::System.Drawing.Point(318, 251);
			label13.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label14 = this.Label3;
			size = new global::System.Drawing.Size(111, 28);
			label14.Size = size;
			this.Label3.TabIndex = 25;
			this.Label3.Text = "Step 2";
			this.Label8.AutoSize = true;
			this.Label8.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label8.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Label8.Image");
			global::System.Windows.Forms.Control label15 = this.Label8;
			location = new global::System.Drawing.Point(286, 84);
			label15.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control label16 = this.Label8;
			size = new global::System.Drawing.Size(195, 11);
			label16.Size = size;
			this.Label8.TabIndex = 26;
			this.Label8.Text = "Download Your Content Pack";
			this.Label9.AutoSize = true;
			this.Label9.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label9.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Label9.Image");
			global::System.Windows.Forms.Control label17 = this.Label9;
			location = new global::System.Drawing.Point(281, 279);
			label17.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control label18 = this.Label9;
			size = new global::System.Drawing.Size(178, 11);
			label18.Size = size;
			this.Label9.TabIndex = 27;
			this.Label9.Text = "Install Your Content Pack";
			this.Label10.AutoSize = true;
			this.Label10.Font = new global::System.Drawing.Font("Minnie", 20.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label10.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Label10.Image");
			global::System.Windows.Forms.Control label19 = this.Label10;
			location = new global::System.Drawing.Point(318, 434);
			label19.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control label20 = this.Label10;
			size = new global::System.Drawing.Size(111, 28);
			label20.Size = size;
			this.Label10.TabIndex = 28;
			this.Label10.Text = "Step 3";
			this.Label11.AutoSize = true;
			this.Label11.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label11.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Label11.Image");
			global::System.Windows.Forms.Control label21 = this.Label11;
			location = new global::System.Drawing.Point(275, 462);
			label21.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control label22 = this.Label11;
			size = new global::System.Drawing.Size(201, 11);
			label22.Size = size;
			this.Label11.TabIndex = 29;
			this.Label11.Text = "Uninstall Your Content Packs";
			this.Label12.AutoSize = true;
			this.Label12.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label12.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Label12.Image");
			global::System.Windows.Forms.Control label23 = this.Label12;
			location = new global::System.Drawing.Point(273, 474);
			label23.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control label24 = this.Label12;
			size = new global::System.Drawing.Size(210, 11);
			label24.Size = size;
			this.Label12.TabIndex = 30;
			this.Label12.Text = "Do not need to download again";
			this.TTRUnistall.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("TTRUnistall.BackgroundImage");
			this.TTRUnistall.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.TTRUnistall.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control ttrunistall = this.TTRUnistall;
			location = new global::System.Drawing.Point(231, 491);
			ttrunistall.Location = location;
			this.TTRUnistall.Name = "TTRUnistall";
			global::System.Windows.Forms.Control ttrunistall2 = this.TTRUnistall;
			size = new global::System.Drawing.Size(116, 28);
			ttrunistall2.Size = size;
			this.TTRUnistall.TabIndex = 31;
			this.TTRUnistall.Text = "TTR";
			this.TTRUnistall.UseVisualStyleBackColor = true;
			this.TTPAUnistall.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("TTPAUnistall.BackgroundImage");
			this.TTPAUnistall.Font = new global::System.Drawing.Font("Minnie", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.TTPAUnistall.ForeColor = global::System.Drawing.Color.Plum;
			global::System.Windows.Forms.Control ttpaunistall = this.TTPAUnistall;
			location = new global::System.Drawing.Point(406, 491);
			ttpaunistall.Location = location;
			this.TTPAUnistall.Name = "TTPAUnistall";
			global::System.Windows.Forms.Control ttpaunistall2 = this.TTPAUnistall;
			size = new global::System.Drawing.Size(116, 28);
			ttpaunistall2.Size = size;
			this.TTPAUnistall.TabIndex = 32;
			this.TTPAUnistall.Text = "TTPA";
			this.TTPAUnistall.UseVisualStyleBackColor = true;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("$this.BackgroundImage");
			size = new global::System.Drawing.Size(746, 535);
			this.ClientSize = size;
			this.Controls.Add(this.TTPAUnistall);
			this.Controls.Add(this.TTRUnistall);
			this.Controls.Add(this.Label12);
			this.Controls.Add(this.Label11);
			this.Controls.Add(this.Label10);
			this.Controls.Add(this.Label9);
			this.Controls.Add(this.Label8);
			this.Controls.Add(this.Label3);
			this.Controls.Add(this.Label2);
			this.Controls.Add(this.HappyDaysTTR);
			this.Controls.Add(this.Button3);
			this.Controls.Add(this.NIGHTLIFETTR);
			this.Controls.Add(this.DIPTTR);
			this.Controls.Add(this.RetoonedTTR);
			this.Controls.Add(this.HappyDaysTTPA);
			this.Controls.Add(this.NightlifeTTPA);
			this.Controls.Add(this.DIPTTPA);
			this.Controls.Add(this.RetoonedTTPA);
			this.Controls.Add(this.Label7);
			this.Controls.Add(this.Label6);
			this.Controls.Add(this.Label5);
			this.Controls.Add(this.Label4);
			this.Controls.Add(this.Label1);
			this.Controls.Add(this.HappyDays);
			this.Controls.Add(this.Nightlife);
			this.Controls.Add(this.Retooned);
			this.Controls.Add(this.DIP);
			this.Name = "ContentPack";
			this.RightToLeftLayout = true;
			this.Text = "Content Pack";
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x0400000E RID: 14
		private global::System.ComponentModel.IContainer components;
	}
}
